In [9]:
# Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [26]:
# Read Dataset
df = pd.read_csv("AirQualityUCI.csv")

In [11]:
# Display Dataset
print(df)

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;
...                                                                                                                                                        ...
;;;;;;;;;;;;;;;;                 NaN                           NaN                              NaN  NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN

[9471 rows x 1 columns]

In [12]:
# First Five Rows
df.head()

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;

In [13]:
# Last Five Rows
df.tail()

                                 Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
;;;;;;;;;;;;;;;; NaN NaN NaN NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN

In [14]:
# Shape of Dataset
print("Shape of Dataset :", df.shape)

Shape of Dataset : (9471, 1)

In [25]:
# Column Names
print(df.columns)

Index(['Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;'], dtype='object')

In [24]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4942 entries, ('10/03/2004;18.00.00;2', '6;1360;150;11', '9;1046;166;1056;113;1692;1268;13', '6;48', '9;0') to ('04/04/2005;14.00.00;2', '2;1071;-200;11', '9;1047;265;654;168;1129;816;28', '5;13', '1;0')
Data columns (total 1 columns):
 #   Column                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                        --------------  -----
 0   Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;  4941 non-null   object
dtypes: object(1)
memory usage: 1.1+ MB

In [23]:
# Data Types
print(df.dtypes)

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;    object
dtype: object

In [22]:
# Statistical Summary
df.describe()

       Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
count                                                4941
unique                                               4941
top                                                5028;;
freq                                                    1

In [21]:
# Check Missing Values
df.isnull().sum()

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;    1
dtype: int64

In [20]:
# Total Missing Values
print("Total Missing Values :", df.isnull().sum().sum())

Total Missing Values : 1

In [19]:
# Duplicate Rows
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [18]:
# Remove Duplicate Rows
df = df.drop_duplicates()

In [17]:
# Check Unique Values
for column in df.columns:
    print(column)
    print(df[column].nunique())
    print("-"*40)

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
4941
----------------------------------------

In [16]:
# Display Random Records
df.sample(10)

                                                                                                                Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
19/05/2004;05.00.00;0               3;848;-200;2                    2;598;32;1219;46;1318;628;17    0;49 2;0                                                9459;;
29/09/2004;06.00.00;0               7;852;-200;4                    0;713;92;1029;53;1203;749;15    2;58 3;0                                                9986;;
14/05/2004;09.00.00;3               3;1148;-200;13                  6;1104;258;723;138;1713;1301;21 0;37 9;0                                                9313;;
08/07/2004;09.00.00;3;1385;-200;18  0;1240;288;596;155;1919;1847;29 5;32                            7;1  3229;;                                                NaN
08/11/2004;15.00.00;1               7;897;-200;7                    8;890;272;850;121;1139;808;11   5;46 4;0                                                6302;;
19/06/2004;08.00.00;1               4;1031;-200;9                   1;945;100;806;86;1697;964;24    6;44 9;1                                                3661;;
24/07/2004;13.00.00;1               2;1058;-200;6                   5;833;47;804;53;1623;626;38     3;27 1;1                                                7970;;
21/08/2004;23.00.00;-200;904;-200;6 7;845;-200;878;-200;1483;775;23 8;44                            7;1  3019;;                                                NaN
13/02/2005;04.00.00;2               8;1515;-200;12                  5;1066;345;508;140;1430;1548;8  9;81 3;0                                                9277;;
12/03/2004;21.00.00;4               4;1598;333;20                   1;1299;274;752;149;1941;1627;12 1;53 3;0                                                7536;;

In [15]:
# Correlation Matrix
df.corr(numeric_only=True)

Empty DataFrame
Columns: []
Index: []